# # open('filename', mode)
# f = open('./files/reading_file_example.txt')
# txt = f.read()
# print(type(txt))
# print(txt)
# # print(f)
# f.close()

f = open('./files/reading_file_example.txt')
lines = f.readlines()
print(type(lines))
print(lines)
f.close()